### ISSUE TITLE
Getter/Setter Reference Binding in Python APIs

### ISSUE THREAD

**Issue by wavefunction91** [NWChemEx/NWXCMake#19]
We ofen expose getter/setter pairs as reference bindings in C++
```
foo.get_set() = bar;
```
Python does not expose this idiom. To expose these types of APIs, we will need to either manually expose symbols that emulate this behaviour, find a way to automatically generate these bindings, or move away from reference binding getter/setter pairs in the C++ API.

**Comment by wavefunction91** [comment]
@keceli @wadejong

**Comment by ryanmrichard** [comment]
I think this opened before the switch to Pybind11. With Pybind11, I think [def_property](https://pybind11.readthedocs.io/en/stable/classes.html#instance-and-static-fields) does what you want. Feel free to reopen if this doesn't solve the issue.
